### ISSUE TITLE
Use of require

### ISSUE THREAD

**Issue by CarmenLexa** [seebigs/faux-sql#1]
I can't use the module , adding require
I am new to nodejs and I have to build a university project with this module but I get this error.

const FauxSQL = require("faux-sql");
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module F:\ProyectoKong\BotKongCliente\node_modules\faux-sql\index.js from F:\ProyectoKong\BotKongCliente\src\db\db.js not supported.  
Instead change the require of index.js in F:\ProyectoKong\BotKongCliente\src\db\db.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (F:\ProyectoKong\BotKongCliente\src\db\db.js:4:17)
    at Object.<anonymous> (F:\ProyectoKong\BotKongCliente\db_index.js:1:12) {
  code: 'ERR_REQUIRE_ESM'
}

How can I solve it?

**Comment by seebigs** [comment]
Hey, this is unfortunately a little complicated... The short answer is that this project uses the newer ES Modules instead of the older CommonJS module pattern (which is the default in most Node versions). The two patterns don't work well together because one imports synchronously and the other asynchronously. Learn more about the differences here: https://blog.logrocket.com/commonjs-vs-es-modules-node-js/

I would suggest that you switch your own project to use ES Modules if you can, but if not, you'll need a workaround like this: https://techsparx.com/nodejs/esnext/dynamic-import.html

**Comment by CarmenLexa** [comment]
thanks for the help, I have already made it work this way. 

const FauxSQL = import("./node_modules/faux-sql/index.js");

(async () => {

    const sql = (await FauxSQL).default({
        filePath: DBSOURCE_LOCAL,
    })
    
    await sql(`
    
    )`);
    const results = await sql('SELECT * FROM campaing');
    console.log(results);
})();

I want to know if INNER JOIN statements work with this module?

**Comment by seebigs** [comment]
INNER JOIN does not work yet, we're working on adding that feature soon

**Comment by CarmenLexa** [comment]
I am willing to give you an incentive in bitcoins if you add the INNER JOIN and RAND statements.

**Comment by seebigs** [comment]
Closing because the original import issue was resolved -AND- the subsequent feature request for INNER JOIN support has also been added as of version 0.3.0
